### PR TITLE
Cleaning up aspects of the fec record articles

### PR DESCRIPTION
**Pull request by noahmanger**
This makes a few of the clean up changes from https://github.com/18F/fec-style/issues/614

- Adds a "Read more" link (needed to use javascript to get it inline)
- Capitalizes the first letter of the categories
image

- When clicking on a tag, it now takes you to the `#feed` div so that the filters are at the top of the screen. 
- Removes the `p--lead` sizing on the first paragraphs.
- If title and email are 'N/A' then they're not displayed on posts

Last, it adds space between the "next item" and the link back to the latest updates page, resolving https://github.com/18F/fec-cms/issues/712:
image

### CODE REVIEW

**Comment by jenniferthibault** [comment]
I should flag that once these changes are made, it's probably best to transfer to @xtine for technical review. I'm 🙅 enough for reviewing js

**Comment by noahmanger** [comment]
Got it! 

image

The reason the ellipsis is showing up as part of the link is because we're truncating after a certain number of words and the link in this case contains more words beyond that limit, so it puts the ellipsis in the middle. That's going to be kind of a weird edge case that just depends on where a link falls in the body of text and how long it is, so I'd prefer if we can just leave it as it would be pretty complicated to implement logic to avoid.

**Comment by noahmanger** [comment]
But I did make it so the underline lines up:
image

**Comment by jenniferthibault** [comment]
Thanks @noahmanger that makes sense to me. Transferring to @xtine for technical review 👋

**Pull request merged**
