### PR TITLE
[WIP] Squash CMS home app migrations

### PR DESCRIPTION
**Pull request by ccostino**
**WIP:  PLEASE DON'T MERGE**

Addresses #743

This changeset is an attempt to clean up our migrations and start from scratch with them.  Our app has grown significantly and the state of the database is very different from when we started.  We hope that in doing this it provides a cleaner base to start from now that we have gotten through a lot of heavy feature development.

### CODE REVIEW

**Comment by ccostino** [comment]
Well, we're still trying to figure out what's going on with this, but we've uncovered where the problem is at least!  It is the migration that adds the `keywords` field to the `RecordPage` models, which is the `0034_auto_20161221_1920` migration.  What is happening is that the migration processing gets down to the point of adding the field itself, and encounters this line (line 392 in `django/db/backends/base/schema.py` within the Django migration framework):

```python
if field.many_to_many and field.remote_field.through._meta.auto_created:
```

`field.remote_field.through` is returning just a string (`home.RecordPageTag`), which does not have a `_meta` attribute on it like a model or object would.  We're trying to figure out what the breakdown is here and why this is the case.  I've asked in the #django Slack channel and we'll continue to do some more research into it.

**Comment by ccostino** [comment]
Also, why this works with our existing migrations but not with this new squashed migration on a fresh database is still a mystery.

**Comment by LindsayYoung** [comment]
Maybe this is Django blasphemy, but what if we look at a db that is up to date, delete all the migration files locally. Then, make a new initial migration, add the "replaces" section  and then name it fec/home/migrations/0001_squashed_0065_auto_20170221_2055.py

**Comment by ccostino** [comment]
🤔 it's cross my mind too, I think it's worth a shot at this point just to see.

**Comment by ccostino** [comment]
I recommend closing this PR and if we decide to come back to it we start fresh, how do others feel?

**Comment by noahmanger** [comment]
Sounds good.

**Pull request closed without merging**
