### PR TITLE
Adding links to transition pages

### PR DESCRIPTION
**Pull request by noahmanger**
This fixes a few empty links I accidentally left earlier and replaces them with transition urls.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Where are the transition urls set?

**Comment by noahmanger** [comment]
@LindsayYoung as an env variable. Defaults to `fec.gov` but can be set to `transition.fec.gov`.

**Comment by noahmanger** [comment]
That change happened earlier.

**Comment by ccostino** [comment]
@noahmanger where is the environment variable set, and how is it pulled into the `settings`?

**Comment by noahmanger** [comment]
https://github.com/18F/fec-cms/blob/transition-links/fec/fec/settings/base.py#L196

**Comment by LindsayYoung** [comment]
Thank you! wanted to confirm since I did not see this before

**Comment by ccostino** [comment]
Thanks, didn't realize it was in another branch!

**Pull request merged**
