### PR TITLE
Editing calendar filters

### PR DESCRIPTION
**Pull request by noahmanger**
- Moves the reporting and compliance periods together with elections and filing deadlines
- Changes label language based on https://github.com/18F/openFEC/issues/1675
- Removes redundant label on legal filter

Resolves https://github.com/18F/fec-cms/issues/307
Resolves https://github.com/18F/openFEC/issues/1675

image

### CODE REVIEW

**Comment by noahmanger** [comment]
Should be merged in after https://github.com/18F/openFEC/pull/1664

**Comment by adborden** [comment]
:+1:

**Comment by emileighoutlaw** [comment]
@noahmanger: Before we merge, would it be possible to get in two tiny copyedits:

1. Lowercase the `p` in `post-election`, under the `Filing deadlines` filter
2. Add an `s` to the end of `Federal election activity periods` under `Reporting and compliance periods` (so that `period` is plural)

?

**Comment by emileighoutlaw** [comment]
Thank you, Jen!

**Comment by jenniferthibault** [comment]
Copy edits incorporated, so this should be ready to merge into the release branch and into develop, which @ccostino suggested, by someone who knows more than Emileigh and I about how to do that :)

**Pull request merged**
