### PR TITLE
[WIP] Feature/agenda model updates

### PR DESCRIPTION
**Pull request by xtine**
Update Agenda page model with more fields to account for executive sunshine notices.
https://github.com/18F/fec-cms/issues/977
https://github.com/18F/fec-cms/issues/980

### CODE REVIEW

**Comment by ccostino** [comment]
Looks like we'll have to account for a migration conflict in this PR too based on the Travis test failure.

**Comment by ccostino** [comment]
I've gotten as far as getting the scraper to work and start processing, however it is getting stuck on an empty anchor element when parsing an executive meeting (sunshine) cell; I've added a [comment in the code ](https://github.com/18F/fec-cms/pull/1009/files#diff-087fc990d82b76e09dfe486fd9482ec7R568) where this is happening and marked it with a `TODO` as the next thing to fix.

**Comment by noahmanger** [comment]
The model updates look good to me, but the scraper isn't working for me. Its crashing at various points. Does it work for you?

**Comment by ccostino** [comment]
I'm sorry, that was probably not clear above - it works for me up until the empty anchor element it hits, but I haven't been able to get it past that yet.

**Comment by noahmanger** [comment]
What do y'all think about closing this PR since we won't be adding this anytime soon?

**Comment by ccostino** [comment]
I haven't had a chance to get back to this at all due to the itemized schedule stuff again.  Are we going to come back to this at all in the future?  If so, I still have the branch locally and can resume work there and file a new PR.

**Comment by noahmanger** [comment]
That's fine. Yeah we will eventually, but not in the near term.

**Pull request closed without merging**
