### PR TITLE
Home content

### PR DESCRIPTION
**Pull request by emileighoutlaw**
Updates the registration and reporting card.

As I was tweaking this I noticed there are just **a lot of words** on the homepage. I did a little pruning along with this update (totally open to others' thoughts on that)

cc @noahmanger 

Resolves: https://github.com/18F/fec-cms/issues/241#event-590820496

### CODE REVIEW

**Comment by noahmanger** [comment]
Closing this since it was merged into the release branch, which we will merge back in to `develop`.

**Comment by emileighoutlaw** [comment]
Hey @noahmanger — does this mean that the content edits that were in this merge *are* taken care of somewhere else?

**Comment by noahmanger** [comment]
Yep. It means that this branch was merged into the release branch, rather than `develop`. Then, we'll merge the release branch back into `develop` and everything will be all together.

**Comment by emileighoutlaw** [comment]
Cool! Thanks so much, Noah!

**Pull request closed without merging**
