### PR TITLE
Fix/tooltip under alignment

### PR DESCRIPTION
**Pull request by xtine**
This fix establishes override properties for the calendar detail tooltips so they are properly aligned on month-at-a-glance view. I also restored the top tooltip arrows so they show up now!

screen shot 2017-11-06 at 10 55 47 pm
screen shot 2017-11-06 at 10 56 10 pm
screen shot 2017-11-06 at 10 55 40 pm

https://github.com/18F/fec-cms/issues/1274

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@xtine in the second screenshot, we seem to have lost the pointy tip of the tooltip altogether, and in the first, it's in a reaaaaaly weird place inside the container. 

Here's an example of the shape from design files, though I if my memory is right, I think the point might have been adjusting it's location to what it was pointing at...can't remember.

screen shot 2017-11-06 at 7 49 16 pm

Is this something we could address in this pass? I'm concerned that having the point inside the calendar tooltip looks unexpected and broken.

**Comment by xtine** [comment]
@jenniferthibault: wow, okay I didn't realize that arrow was wrong (just an interesting design 😆) because I've never worked with the calendar tooltip before. Can you post what it should look like in here?

And yeah some time even before merge the tooltip point was lost. I can definitely work on getting that back. I assume the point should just be below the (i) icon in the filter label?

**Comment by jenniferthibault** [comment]
My memory isn't total garbage! It did used to move! 

https://github.com/18F/fec-style/pull/474

I'm trying to hunt down what the design is for the tooltip in the calendar grid view, because the overlapping close X and the event title are off too. Hold plz while I dig some old issues up.

**Comment by jenniferthibault** [comment]
@xtine via https://github.com/18F/FEC/issues/561 I found an old image of what the grid view tooltip is supposed to look like:

screen shot 2017-11-06 at 8 22 43 pm


You're right about the point—it should be directly centered under the thing that initiates it opening, which is either the circular information icon, or the calendar event

**Comment by jenniferthibault** [comment]
And here are additional Calendar tooltip PRs that I found while looking, in case they're helpful:
- https://github.com/18F/fec-style/pull/445
- https://github.com/18F/fec-style/pull/546
- https://github.com/18F/fec-style/pull/402
- https://github.com/18F/fec-style/pull/474

**Comment by xtine** [comment]
@jenniferthibault: thanks for digging up the old PRs and calendar detail design, I found out that the override properties for calendar detail tooltip weren't showing up so I added specificity to match the designs.
Also looking at the stylesheets I noticed that the old tooltip svgs were missing from the latest fec-style so I restored those as well.

**Comment by xtine** [comment]
@jenniferthibault: I think we should make a non-dependent task. We need to migrate pattern library to circle and I still need to make a style asset migration script so those need to be done first of course. If those weren't issues I would be up for a documentation step but we are a bit behind already.

**Comment by jenniferthibault** [comment]
Sounds good, I just made that a separate, non-dependent issue in the pattern library for fixing the busted tooltips based on the work that happened in this PR 👍 

https://github.com/18F/fec-pattern-library/issues/20

**Pull request merged**
