### PR TITLE
New page templates

### PR DESCRIPTION
**Pull request by noahmanger**
This updates the styles for the new landing page and checklist page templates. 

image

image

Depends on https://github.com/18F/fec-style/pull/196
Resolves https://github.com/18F/fec-style/issues/192
Resolves https://github.com/18F/fec-style/issues/193

Still need to figure out the sticky, scroll-tracking menu situation. If I figure it out before anyone can review this, I'll roll it in; otherwise, let's merge and then do that in a subsequent PR.

### CODE REVIEW

**Comment by jenniferthibault** [comment]
A few small things left, but otherwise it's looking good @noahmanger :

The Resources panel on the essentials page is showing a broken image link for me:

screen shot 2015-12-02 at 10 27 47 am


And the sidebar on the essentials page just needs to match up to the design a leeeeetle more. It's close! 
- Headers should be uppercase
- Copy items Karla regular (just like they are in the bulleted lists, but not bulleted here)

screen shot 2015-12-02 at 10 27 20 am

Thanks for getting this in such good shape!

**Comment by noahmanger** [comment]
The image thing will be fixed when we merge the style changes, as the cms gets all its images from that repo. 

Is all text in sidebars Karla?

**Comment by jenniferthibault** [comment]
The other place we use these sidebars is for Legal Resources on each article page. There's some discussion of what actually goes into these here https://github.com/18F/fec-cms/issues/136#issuecomment-161039720

The main body copy I've used for this is Karla regular, the one exception being that intro line "Full-text campaign finance regulations." but that could be changed if it doesn't make sense. Thoughts or feedback on the typography here welcome!

**Comment by noahmanger** [comment]
Cool. I'm just going to set the font family for all sidebars.

**Comment by noahmanger** [comment]
Hokay ready.

**Comment by jenniferthibault** [comment]
Awesome, thanks Noah!

**Pull request merged**
