### PR TITLE
New contact info for info division

### PR DESCRIPTION
**Pull request by johnnyporkchops**
For option 2 on https://github.com/18F/fec-cms/issues/1159#issuecomment-319652593

### CODE REVIEW

**Comment by johnnyporkchops** [comment]
PLEASE DONT MERGE - changes requested

**Comment by johnnyporkchops** [comment]
PLEASE MERGE, issues resolved

**Comment by jenniferthibault** [comment]
@johnnyporkchops could you please post a screenshot of the final page?

**Comment by johnnyporkchops** [comment]
The spacing has been corrected:
info-div-contact-spacing

**Comment by jenniferthibault** [comment]
Thank you! The styling here looks awesome. Visual design review = ✅ 
Front end review needed

**Comment by dorothyyeager** [comment]
Thank you @johnnyporkchops @jenniferthibault it looks great!

**Pull request merged**
