### PR TITLE
Added validation for no RAD analyst results

### PR DESCRIPTION
**Pull request by patphongs**
This resolves https://github.com/18F/fec-cms/issues/1142

Adds validation for no RAD analyst

rad-analyst-validation

### CODE REVIEW

**Comment by jenniferthibault** [comment]
Hold for review until Lauren takes a look over in #1142

**Comment by noahmanger** [comment]
Just flagging this will also need updated tests in `/tests/contact-form.js` . Just glanced at the code and it looks good.

**Comment by jenniferthibault** [comment]
👍 from Lauren in #1142 , so remaining task is adding tests & test review.

**Comment by patphongs** [comment]
Closing this PR in favor of PR https://github.com/18F/fec-cms/pull/1269. This was necessary to incorporate merged webapp and cms code.

**Pull request closed without merging**
