### PR TITLE
Adds tooltip content to calendar events

### PR DESCRIPTION
**Pull request by noahmanger**
Adds support for category tooltips in list view.

image

Requires https://github.com/18F/fec-style/pull/402
Resolves https://github.com/18F/fec-cms/issues/337

### CODE REVIEW

**Comment by emileighoutlaw** [comment]
The content looks great here. We'll have to take out the definition for EC and IE periods— we're still working on building support for these. :( But everything else can get implemented and launched.

**Comment by noahmanger** [comment]
We're not planning on including this in this week's release, and I think that's fine.

**Comment by emileighoutlaw** [comment]
Sounds good. Just wanted to make sure we don't accidentally release it later. I'll keep trucking on this :)

**Comment by emileighoutlaw** [comment]
I added in the reporting tooltip. 

I believe this PR is ready for a merge (Although I'll wait for Noah to get back and add the `plz-review` label, just to be sure). 

Resolves: https://github.com/18F/fec-cms/issues/337

**Comment by noahmanger** [comment]
This is now done and read to review. Maybe @ccostino or @xtine has a moment for a quick code review?

**Comment by ccostino** [comment]
This looks good, thanks @noahmanger!

**Pull request merged**
