### PR TITLE
case insensitive filter for hearings titles

### PR DESCRIPTION
**Pull request by johnnyporkchops**
Issue: #1239
All hearings were not showing up in the hearings tab of /meetings because the filter was case sensitive, returning on titles containing "Hearing", but not "hearing" which is the sentence-case convention for newly created meetings.

- [ ] Note: After this is deployed, the few 2017 hearings titles that exist should be changed back to sentence-case (they are capitalized now so they show up in the tab)

### CODE REVIEW

**Comment by ccostino** [comment]
@xtine and @LindsayYoung:  Do you have a sense of why the npm tests are failing here?  Or is this due to the CircleCI config not being quite done yet?

**Comment by xtine** [comment]
@johnnyporkchops: can you merge in latest develop?

**Comment by johnnyporkchops** [comment]
If this has become stale, I can create a new PR, it is a one-file, one-line change.

**Comment by ccostino** [comment]
@johnnyporkchops, you can either do that or just pull the latest changes in `develop` and merge them back in here.  Whichever is easier for you, and once that's done we can merge the change in.  Like you said, it's just the one line changing case insensitivity. :-)

**Pull request merged**
