### PR TITLE
Set `Secure` and `HttpOnly` flags on cookies.

### PR DESCRIPTION
**Pull request by jmcarp**
Should resolve cookie security issues raised in slack at https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1510695955000310. Please test before merging--I pulled this from the django docs but haven't had time to verify manually.

@LindsayYoung

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Issue https://github.com/18F/fec-proxy/issues/67

**Comment by jmcarp** [comment]
@lbeaufort: to verify, you'll need to run with the production config, then check your session and csrf cookies and verify that they're both setting the `Secure` and `HttpOnly` flags. This will be hard to test locally, since you're probably not using https there, meaning that `Secure` cookies won't be sent at all. You might want to test in a development space instead.

**Comment by jenniferthibault** [comment]
@LindsayYoung I just noticed that you applied the `Before release` label to this. Are you intending it to be added in time for the 11/21 release or the following?

**Comment by patphongs** [comment]
@LindsayYoung I suggest we merge this into develop to test first and then if it works well, we can make a separate PR to merge into the release?

**Comment by patphongs** [comment]
Merging this into dev for testing

**Comment by patphongs** [comment]
Thanks @jmcarp! I have confirmed that the `csrftoken` cookie is now secure on dev. A new PR has been submitted for review and merge into our next release: https://github.com/18F/fec-cms/pull/1509

**Pull request merged**
