### PR TITLE
remove Ravel from homepage

### PR DESCRIPTION
**Pull request by johnnyporkchops**

### CODE REVIEW

**Comment by noahmanger** [comment]
Does this need to be deployed to production ASAP?

**Comment by johnnyporkchops** [comment]
I don't think so

**Comment by AmyKort** [comment]
Sorry, weighing in late. Yes. It needs to be deployed to production as fast as possible.

**Comment by AmyKort** [comment]
My apologies to John for being a slow communicator.

**Comment by noahmanger** [comment]
Since this is going into production, this should be branched off of `master` rather than `develop`. Closing this to be replaced be a clean hotfix.

**Pull request closed without merging**
